### PR TITLE
⚒ fix push for "-b" - flag

### LINKED ISSUE #10: set upstream branch on push
if git-pick creates a new branch git-pick have to set the upstream branch
`git push --set-upstream origin ${branchname}`

### PR DESCRIPTION
**Pull request by chrishelgert**
this pr adds the "--set-upstream" (-u) flag on push for new branches.

fixes #10

### CODE REVIEW

File: __tests__/lib/git-test.js [hunk 1]
```diff
@@ -146,17 +146,17 @@ describe('git.js', () => {
     })
   })
 
-  describe('function push()', () => {
-    test('calls shell.exec with "git pull"', () => {
-      git.pull()
-      expect(shell.exec).toBeCalledWith('git pull')
+  describe('function pushUpstream()', () => {
+    test('calls shell.exec with "git push -u" with the given branch', () => {
```
Comment (danielbayerlein) [inline __tests__/lib/git-test.js]: `'calls shell.exec with "git push -u origin" with the given branch'`

File: lib/index.js [hunk 2]
```diff
@@ -71,7 +70,11 @@ function exec (commit, branches, options) {
     git.cherryPick(commit)
 
     // Push the changes to the remote repository
-    git.push()
+    if (options.newBranch) {
+      git.pushUpstream(branchName)
+    } else {
+      git.push(options.newBranch)
```
Comment (danielbayerlein) [inline lib/index.js]: `git.push` does not expect any parameters.
